services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - db:/var/lib/postgresql/data
  web:
    tty: true
    stdin_open: true
    image: library
    container_name: library
    build:
      context: .
    env_file:
      - .env
    command: >
      sh -c "rm -f tmp/pids/server.pid &&
             bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
      - "$DOCKER_COMPOSE_ARCHIVE_FOLDER:/rails/db/data"
    networks:
      - default
    ports:
      - "8080:3000"
    depends_on:
      - db
    environment:
      RAILS_LOG_TO_STDOUT: 'yes'
      PAGER: 'more'
      POSTGRES_HOST: 'db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    networks:
      - default
    volumes:
      - ./data/mongodb:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: mongoroot
    #   MONGO_INITDB_ROOT_PASSWORD: mongosecret
    links:
      - "db:db"
      - "web:web"
    ports:
      - "27017:27017"
volumes:
  db:
