default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('DB_POOL') { 1 } %>
  prepared_statements: false

postgre: &postgre
  port: <%= ENV.fetch('POSTGRES_PORT', '5432') %>
  username: <%= ENV.fetch('POSTGRES_USER') { 'postgres' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'postgres' } %>

development:
  primary:
    <<: *default
    <<: *postgre
    host: <%= ENV.fetch('POSTGRES_HOST_MASTER', 'localhost') %>
    database: library_development
  primary_replica:
    <<: *default
    <<: *postgre
    host: <%= ENV.fetch('POSTGRES_HOST_SLAVE', 'localhost') %>
    database: library_development
    replica: true

test:
  <<: *default
  <<: *postgre
  host: <%= ENV.fetch('POSTGRES_HOST_MASTER', 'localhost') %>
  database: library_test

production:
  <<: *default
  <<: *postgre
  host: <%= ENV.fetch('POSTGRES_HOST_MASTER', 'localhost') %>
  database: library_production
